### ISSUE TITLE
fbgemm_t856_bs65536.pt VS fbgemm_t856_bs65536_0.pt

### ISSUE THREAD

**Issue by rishucoding** [facebookresearch/dlrm_datasets#10]
Hi, 

In the two datasets: fbgemm_t856_bs65536.pt and fbgemm_t856_bs65536_0.pt: the number of indices is very different. While all the files fbgemm_t856_bs65536_{0 ... 15}.pt share a similar number of indices, about 468Million. Could you elaborate on this deviation? 

Thanks,
Rishabh Jain

**Comment by yifanliu112** [comment]
Hi @rishucoding,

Your observation is correct. `fbgemm_t856_bs65536.pt` and `fbgemm_t856_bs65536_{0 ... 15}.pt` were created at two different times (a few months apart). You can think of them as batches for the same model, but the underlying data has changed over time. Both are valid datasets and characterize production recommendation workloads at different times.

**Comment by yifanliu112** [comment]
Close this issue due to inactivity.
