### ISSUE TITLE
How to estimate total number of rows in a table?

### ISSUE THREAD

**Issue by joshivm22** [facebookresearch/dlrm_datasets#8]
Hi,
   I am computing total number of rows per table by tracking the maximum index looked up across 17 batches. Is this a correct way to estimate the total number of rows in a table? If no, could you please shed some light on this?

**Comment by yifanliu112** [comment]
Hi @joshivm22,

Thanks for the interest. Yes, using the largest index looked up gives an estimation of the number of rows in a table and it should be accurate enough. We will also consider including the exact dimensions in the next release for each table if necessary.

**Comment by joshivm22** [comment]
Thanks for the reply.
